### ISSUE TITLE
Improve the README file to add a reference to main content page

### ISSUE THREAD

**Issue by chanakaudaya** [wso2/ETAC#1]
**Description:**
At the moment, if someone visit the main github repository URL of this project, visitor will see only "ETAC" word which is the only content within the README file. It is always good to have a meaningful README file. In this case, we can add a small description and a reference to the original content page so that the visitor is redirected to the correct page. 
**Suggested Labels:**
improvement

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by srinathperera** [comment]
this is fixed.
